path:
  ckpt_path: "/scratch/s5962080/FastSpeech2_new/Thesis_commonvoice/output/ckpt/twlj"
  log_path: "/scratch/s5962080/FastSpeech2_new/Thesis_commonvoice/output/log/twlj"
  result_path: "/scratch/s5962080/FastSpeech2_new/Thesis_commonvoice/output/result/twlj"
  preprocessed_path: "/scratch/s5962080/FastSpeech2_new/Thesis_commonvoice/preprocessed_data/twlj_mix"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 50000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 10000
model:
  use_speaker_embedding: true
  n_speaker: 2

preprocessing:
  use_phoneme_input: true
  text_cleaners: []